# Change prefix from 'Ctrl+B' to 'Ctrl+A'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Enable mouse
set -g mouse on

# Shift Alt vim Keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Open current folder in new session
bind c new-window -c "#{pane_current_path}"

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

# Create shortcut to resource the tmux file
bind r source-file $HOME/.config/tmux/tmux.conf

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# vim-like splits
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# unbind the default detatch
unbind d

# Detach is now bound to prefix + shift + d
bind-key D detach-client

# Open Lazydocker in new tab with the prefix + d
bind-key d new-window -n lazydocker "lazydocker"

set -g @plugin "janoamaral/tokyo-night-tmux"

run '~/.tmux/plugins/tpm/tpm'
