###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$fileManager = $terminal --class=Yazi -e yazi
$menu = rofi -show drun -theme tokyonight
$browser = firefox

